[build]
  publish    = "public"                    # your static dir
  functions  = "netlify/functions"         # where your Go binaries land
  command    = "npm run build:functions"   # compile Go before deploy

# Proxy all /api/* calls to the matching function
# e.g. GET /api/auth → netlify/functions/auth
[[redirects]]
  from     = "/api/*"
  to       = "/.netlify/functions/:splat"
  status   = 200
  force    = true
